baseurl = "/"
languageCode = "pt-br"
title = "Gabriela Caesar"
theme = "hugo-theme-hello-friend"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

description = "Site de Gabriela Caesar"
keywords = "jornalismo de dados, jornalismo, data journalism, ddj, data drive journalism, reporter, g1, programação, r, rstudio"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[author]
  name = "Gabriela Caesar"

[[menu.main]]
    name = "Sobre"
    url = "/about/"
[[menu.main]]
    name = "Trabalhos"
    url = "/works/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/gabrielacaesar"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/gabrielacaesar"

[params]
    homeSubtitle = "Jornalista de dados"
    description = "Gabriela Caesar"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    width = 50
    height = 50
    alt = "Logo"
    logoText = "gabriela caesar"
    logoHomeLink = "/"
